/* ============================================
   SAGA HERBALS - DATA & LANGUAGE FILE
   Edit products, prices, and translations here
   ============================================ */

const SHOP_DATA = {

  // ---- CONTACT ----
  whatsapp: "919952427492",
  instagram: "https://www.instagram.com/saga_herbels_organic_protect",
  facebook: "https://www.facebook.com/sagaherbals",

  // ---- PRODUCTS ----
  products: [
    {
      id: 1,
      emoji: "🌿",
      nameEN: "Herbal Bathing Powder",
      nameTM: "மூலிகை குளியல் பொடி",
      descEN: "100% organic herbal bath powder made from natural herbs. Safe for children and adults. Cleanses, nourishes and leaves skin glowing.",
      descTM: "இயற்கை மூலிகைகளால் தயாரிக்கப்பட்ட 100% ஆர்கானிக் குளியல் பொடி. குழந்தைகளுக்கும் பெரியவர்களுக்கும் பாதுகாப்பானது.",
      price: 199,
      originalPrice: 299,
      badge: "Best Seller",
      tags: ["100% Organic", "Child Safe", "No Chemicals"],
      category: "bath"
    },
    {
      id: 2,
      emoji: "☀️",
      nameEN: "Sunlight-Infused Hair Growth Oil",
      nameTM: "சூரிய ஒளி முடி வளர்ச்சி எண்ணெய்",
      descEN: "Specially crafted hair oil infused with sunlight energy and pure herbal extracts. Promotes hair growth and reduces hair fall.",
      descTM: "சூரிய ஆற்றல் மற்றும் மூலிகை சாறுகளால் தயாரிக்கப்பட்ட சிறப்பு எண்ணெய். முடி வளர்ச்சியை அதிகரிக்கும்.",
      price: 349,
      originalPrice: 499,
      badge: "New",
      tags: ["Hair Growth", "Herbal", "Natural"],
      category: "hair"
    },
    {
      id: 3,
      emoji: "🌺",
      nameEN: "Herbal Baby Bath Powder",
      nameTM: "மூலிகை குழந்தை குளியல் பொடி",
      descEN: "Extra gentle herbal bath powder specially formulated for babies. No harsh chemicals, pure herbs only. Keeps baby skin soft and healthy.",
      descTM: "குழந்தைகளுக்காக சிறப்பாக தயாரிக்கப்பட்ட மென்மையான மூலிகை குளியல் பொடி. இரசாயனமில்லாத தூய மூலிகைகள் மட்டும்.",
      price: 249,
      originalPrice: 349,
      badge: "Child Safe",
      tags: ["Baby Safe", "Gentle", "Pure Herbs"],
      category: "bath"
    },
    {
      id: 4,
      emoji: "🍃",
      nameEN: "Anti Hair Fall Herbal Pack",
      nameTM: "முடி உதிர்வு தடுப்பு மூலிகை பேக்",
      descEN: "Powerful herbal pack to control hair fall caused by stress, nutrition deficiency and pollution. Made with traditional Ayurvedic herbs.",
      descTM: "மன அழுத்தம், சத்து குறைபாடு மற்றும் மாசு காரணமாக ஏற்படும் முடி உதிர்வை கட்டுப்படுத்த சக்திவாய்ந்த மூலிகை பேக்.",
      price: 299,
      originalPrice: 449,
      badge: "Popular",
      tags: ["Anti Hair Fall", "Ayurvedic", "Herbal"],
      category: "hair"
    },
    {
      id: 5,
      emoji: "✨",
      nameEN: "Skin Brightening Herbal Powder",
      nameTM: "சருமம் பளபளக்க மூலிகை பொடி",
      descEN: "Natural herbal powder that brightens skin tone, removes tan and gives a healthy glow. Suitable for all skin types.",
      descTM: "சருமத்தை பொலிவாக்கி, கருமையை நீக்கி ஆரோக்கியமான பொலிவை தரும் மூலிகை பொடி. அனைத்து சருமங்களுக்கும் ஏற்றது.",
      price: 229,
      originalPrice: 329,
      badge: "Trending",
      tags: ["Skin Brightening", "All Skin Types", "Natural"],
      category: "skin"
    },
    {
      id: 6,
      emoji: "🌱",
      nameEN: "Combo Pack (Bath + Hair Oil)",
      nameTM: "காம்போ பேக் (குளியல் + எண்ணெய்)",
      descEN: "Get our bestselling Herbal Bathing Powder and Hair Growth Oil together at a special combo price. Complete herbal care routine.",
      descTM: "எங்களின் சிறந்த மூலிகை குளியல் பொடி மற்றும் முடி வளர்ச்சி எண்ணெயை சிறப்பு விலையில் பெறுங்கள்.",
      price: 499,
      originalPrice: 648,
      badge: "Save ₹149",
      tags: ["Combo Offer", "Best Value", "Complete Care"],
      category: "combo"
    }
  ],

  // ---- REVIEWS ----
  reviews: [
    { stars: 5, textEN: "The herbal bathing powder is amazing! My skin feels so soft and fresh. My daughter uses it too and she loves it. Completely natural, no irritation.", textTM: "மூலிகை குளியல் பொடி அற்புதமாக இருக்கிறது! என் சருமம் மிகவும் மென்மையாகவும் புத்துணர்ச்சியாகவும் உணர்கிறேன்.", author: "Priya R.", location: "Chennai" },
    { stars: 5, textEN: "Hair oil is genuinely effective. I noticed less hair fall within 2 weeks of use. The product smells wonderful and is very pure.", textTM: "முடி எண்ணெய் உண்மையிலேயே பயனுள்ளதாக இருக்கிறது. 2 வாரங்களில் முடி உதிர்வு குறைந்தது.", author: "Kavitha S.", location: "Coimbatore" },
    { stars: 5, textEN: "Ordered the baby bath powder for my 6-month-old. It's so gentle and natural. My baby's skin is smooth and healthy. Will order again!", textTM: "என் குழந்தைக்கு குளியல் பொடி வாங்கினேன். மிகவும் மென்மையாகவும் இயற்கையாகவும் உள்ளது.", author: "Meena K.", location: "Madurai" },
    { stars: 5, textEN: "Loved the combo pack! Great value for money. The packaging is beautiful and delivery was fast. Highly recommend Saga Herbals.", textTM: "காம்போ பேக் மிகவும் பிடித்தது! பணத்திற்கு மதிப்பான பொருள். சேகா ஹெர்பல்ஸை மிகவும் பரிந்துரைக்கிறேன்.", author: "Lakshmi V.", location: "Tiruchirappalli" },
    { stars: 5, textEN: "Pure organic products, no chemicals. My whole family uses the bath powder now. The owner is very responsive on WhatsApp too.", textTM: "தூய ஆர்கானிக் பொருட்கள், ரசாயனம் இல்லை. என் குடும்பம் முழுவதும் இப்போது குளியல் பொடியை பயன்படுத்துகிறோம்.", author: "Sudha M.", location: "Salem" },
    { stars: 5, textEN: "Skin brightening powder really works! I've been using it for a month and people are asking me what I'm doing differently. Very happy!", textTM: "சருமம் பளபளக்க பொடி உண்மையிலேயே வேலை செய்கிறது! ஒரு மாதமாக பயன்படுத்துகிறேன், மாற்றம் தெரிகிறது.", author: "Ranjani P.", location: "Erode" }
  ],

  // ---- LANGUAGE STRINGS ----
  lang: {
    EN: {
      navHome: "Home",
      navProducts: "Products",
      navAbout: "About",
      navContact: "Contact",
      heroTitle: "Pure Nature,\nRadiant You",
      heroTitleSpan: "Radiant You",
      heroBadge: "100% Organic & Natural",
      heroSub: "Handcrafted herbal products made with love — safe for your family, kind to the earth.",
      heroBtn1: "Shop Now",
      heroBtn2: "WhatsApp Us",
      stat1Num: "200+", stat1Label: "Happy Customers",
      stat2Num: "100%", stat2Label: "Organic",
      stat3Num: "10+", stat3Label: "Products",
      trustFree: "Free Shipping ₹500+",
      trustOrganic: "100% Organic",
      trustSafe: "Child Safe",
      trustDelivery: "Fast Delivery",
      trustAuth: "Authentic Herbs",
      productsTitle: "Our Products",
      productsSub: "Handcrafted with pure herbs and natural ingredients",
      addToCart: "Add to Cart",
      featuresTitle: "Why Choose Saga Herbals?",
      featuresSub: "We believe nature has everything you need",
      reviewsTitle: "What Our Customers Say",
      reviewsSub: "Real reviews from happy customers",
      aboutTitle: "Our Story",
      aboutSub: "Founded with love, grown with nature",
      aboutP1: "Saga Herbals was born from a simple belief — that nature provides the best care for our bodies. Founded by a passionate herbalist, every product is handcrafted using traditional recipes passed down through generations.",
      aboutP2: "We source only the finest organic herbs, ensure zero harmful chemicals, and make products that are safe for your entire family including your little ones.",
      contactTitle: "Get In Touch",
      contactSub: "We'd love to hear from you",
      whatsappTitle: "Order on WhatsApp",
      whatsappSub: "Chat with us directly to place your order, ask about products, or get personalized recommendations.",
      cartTitle: "Your Cart",
      cartEmpty: "Your cart is empty",
      cartEmptySub: "Add some herbal goodness!",
      subtotal: "Subtotal",
      checkout: "Checkout",
      orderWhatsapp: "Order via WhatsApp",
      checkoutTitle: "Complete Your Order",
      fullName: "Full Name",
      phone: "Phone Number",
      address: "Delivery Address",
      city: "City",
      pincode: "Pincode",
      notes: "Order Notes (optional)",
      paymentMethod: "Payment Method",
      payUPI: "UPI / GPay / PhonePe",
      payRazorpay: "Razorpay (Card / Net Banking / UPI)",
      payCOD: "Cash on Delivery",
      payBank: "Bank Transfer",
      placeOrder: "Place Order",
      orderSummary: "Order Summary",
      footerTagline: "Pure • Organic • Natural",
      footerDesc: "Handcrafted herbal products for your family. 100% organic, child safe, and made with love.",
      footerShop: "Shop",
      footerHelp: "Help",
      footerFollow: "Follow Us",
      footerCopy: "© 2025 Saga Herbals. All rights reserved. Made with 🌿 love.",
    },
    TM: {
      navHome: "முகப்பு",
      navProducts: "பொருட்கள்",
      navAbout: "எங்களைப் பற்றி",
      navContact: "தொடர்பு",
      heroTitle: "இயற்கையின் கொடை,\nஉங்கள் அழகு",
      heroTitleSpan: "உங்கள் அழகு",
      heroBadge: "100% ஆர்கானிக் & இயற்கை",
      heroSub: "அன்போடு தயாரிக்கப்பட்ட மூலிகை பொருட்கள் — உங்கள் குடும்பத்திற்கு பாதுகாப்பானது, பூமிக்கு மென்மையானது.",
      heroBtn1: "இப்போது வாங்க",
      heroBtn2: "வாட்ஸ்ஆப்பில் தொடர்பு கொள்ள",
      stat1Num: "200+", stat1Label: "மகிழ்ச்சியான வாடிக்கையாளர்கள்",
      stat2Num: "100%", stat2Label: "ஆர்கானிக்",
      stat3Num: "10+", stat3Label: "பொருட்கள்",
      trustFree: "₹500+ இலவச டெலிவரி",
      trustOrganic: "100% ஆர்கானிக்",
      trustSafe: "குழந்தைகளுக்கு பாதுகாப்பு",
      trustDelivery: "வேகமான டெலிவரி",
      trustAuth: "உண்மையான மூலிகைகள்",
      productsTitle: "எங்கள் பொருட்கள்",
      productsSub: "தூய மூலிகைகள் மற்றும் இயற்கை பொருட்களால் தயாரிக்கப்பட்டது",
      addToCart: "கார்ட்டில் சேர்",
      featuresTitle: "சேகா ஹெர்பல்ஸை ஏன் தேர்வு செய்ய வேண்டும்?",
      featuresSub: "இயற்கையில் உங்களுக்கு தேவையான அனைத்தும் உள்ளது என்று நாங்கள் நம்புகிறோம்",
      reviewsTitle: "வாடிக்கையாளர்கள் என்ன சொல்கிறார்கள்",
      reviewsSub: "மகிழ்ச்சியான வாடிக்கையாளர்களின் உண்மையான மதிப்புரைகள்",
      aboutTitle: "எங்கள் கதை",
      aboutSub: "அன்போடு தொடங்கப்பட்டது, இயற்கையுடன் வளர்ந்தது",
      aboutP1: "சேகா ஹெர்பல்ஸ் ஒரு எளிய நம்பிக்கையிலிருந்து பிறந்தது — இயற்கை நம் உடல்களுக்கு சிறந்த பராமரிப்பை வழங்குகிறது. ஒரு ஆர்வமிக்க மூலிகை வல்லுநரால் நிறுவப்பட்டது, ஒவ்வொரு பொருளும் தலைமுறைகளாக கடந்துவரும் பாரம்பரிய சமையல் குறிப்புகளைப் பயன்படுத்தி கைத்தொழிலாக தயாரிக்கப்படுகிறது.",
      aboutP2: "நாங்கள் சிறந்த ஆர்கானிக் மூலிகைகளை மட்டுமே பயன்படுத்துகிறோம், தீங்கு விளைவிக்கும் ரசாயனங்கள் இல்லை என்பதை உறுதிசெய்கிறோம், மற்றும் உங்கள் குழந்தைகள் உட்பட உங்கள் முழு குடும்பத்திற்கும் பாதுகாப்பான பொருட்களை தயாரிக்கிறோம்.",
      contactTitle: "தொடர்பு கொள்ளுங்கள்",
      contactSub: "உங்களிடமிருந்து கேட்க விரும்புகிறோம்",
      whatsappTitle: "வாட்ஸ்ஆப்பில் ஆர்டர் செய்யுங்கள்",
      whatsappSub: "உங்கள் ஆர்டரை வைக்க, பொருட்களைப் பற்றி கேட்க அல்லது தனிப்பட்ட பரிந்துரைகளைப் பெற நேரடியாக அரட்டையடியுங்கள்.",
      cartTitle: "உங்கள் கார்ட்",
      cartEmpty: "உங்கள் கார்ட் காலியாக உள்ளது",
      cartEmptySub: "சில மூலிகை நன்மைகளை சேர்க்கவும்!",
      subtotal: "மொத்தம்",
      checkout: "செக்அவுட்",
      orderWhatsapp: "வாட்ஸ்ஆப்பில் ஆர்டர்",
      checkoutTitle: "உங்கள் ஆர்டரை முடிக்கவும்",
      fullName: "முழு பெயர்",
      phone: "தொலைபேசி எண்",
      address: "டெலிவரி முகவரி",
      city: "நகரம்",
      pincode: "பின்கோட்",
      notes: "ஆர்டர் குறிப்புகள் (விரும்பினால்)",
      paymentMethod: "பணம் செலுத்தும் முறை",
      payUPI: "UPI / GPay / PhonePe",
      payRazorpay: "Razorpay (கார்டு / நெட் பேங்கிங் / UPI)",
      payCOD: "கேஷ் ஆன் டெலிவரி",
      payBank: "வங்கி பரிமாற்றம்",
      placeOrder: "ஆர்டர் செய்யுங்கள்",
      orderSummary: "ஆர்டர் சுருக்கம்",
      footerTagline: "தூய்மை • ஆர்கானிக் • இயற்கை",
      footerDesc: "உங்கள் குடும்பத்திற்கான கைத்தொழில் மூலிகை பொருட்கள். 100% ஆர்கானிக், குழந்தைகளுக்கு பாதுகாப்பானது.",
      footerShop: "கடை",
      footerHelp: "உதவி",
      footerFollow: "பின்தொடரவும்",
      footerCopy: "© 2025 சேகா ஹெர்பல்ஸ். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. 🌿 அன்போடு தயாரிக்கப்பட்டது.",
    }
  }
};
